# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/anatol/vmtest
%global goipath         github.com/anatol/vmtest
%global commit          7a42f1f6d7b839347ce996b121aa066369cd6b42

%gometa -f

%global common_description %{expand:
Go framework for integration testing with Virtual machines (e.g. QEMU).}

%global golicenses      LICENSE
%global godocs          docs README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Go framework for integration testing with Virtual machines (e.g. QEMU)
License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%gopkgfiles

%changelog
%autochangelog
